language: go

os:
  - linux
  - windows
go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.5"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.x"

notifications:
  irc:
    if: repo = namecoin/certinject
    channels:
      - "chat.freenode.net#namecoin-dev"
    on_success: never

jobs:
  allow_failures:
    - stage: lint
  include:
    - os: linux
      stage: lint
      language: go
      go: "1.14.x"
      script:
        - go get -v -d -t ./...
        - bash testdata/golangci-linter.bash

stages:
  - lint
  - test

# 'test' stage
script:
  # workaround for no module support, we copy this run's source code into namecoin/certinject
  - env
  - if [ "$TRAVIS_REPO_SLUG" != "namecoin/certinject" ] && [ "$TRAVIS_GO_VERSION" = "1.10.x" ]; then \
      mkdir $GOPATH/src/github.com/namecoin; \
      cp -av . $GOPATH/src/github.com/namecoin/certinject; \
      cd $GOPATH/src/github.com/namecoin/certinject; fi
  # windows ssl test
  - if [ "$TRAVIS_OS_NAME" = 'windows' ]; then bash testdata/travis.bash; fi
  # go test
  - go get -v -d -t ./...
  - go test -v ./...

env:
  global:
    # GITHUB_TOKEN for automatic releases
    - secure: "at1oJs7ib7glx3W+zk+OkT041LdknVXirIhN403CIihVUrlOhODY7yCTgvF4Rk0jYBJiT35Q2qxpgfWF2qGnsNsQmjG3ydDWQDCepDc/CgXfLyoiSTJK5vTK72dYWTVsBTycXbj1CbSy2X2ah/KWjc4RcgZ67ER7mDpRU5nFeow="
    # Set this to the Go version to use for releases (must appear in version list above).
    - RELEASE_GO_VERSION="1.x"
    # Go versions before go1.13.x will grab master branch unless we use GO111MODULE=on
    # (go1.10.x still needs the above workaround)
    - GO111MODULE="on"
