language: go

os:
  - windows
  - linux
go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.5"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.x"

notifications:
  irc:
    if: repo = namecoin/certinject
    channels:
      - "chat.freenode.net#namecoin-dev"
    on_success: never

jobs:
  allow_failures:
    - stage: lint
  include:
    - os: linux
      stage: lint-new
      language: go
      go: "1.14.x"
      script:
        # lint new changes
        - go get -v -d -t ./...
        - bash testdata/golangci-linter.bash --new-from-rev=HEAD~ # new changes
    - os: linux
      stage: lint
      language: go
      go: "1.14.x"
      script:
        # lint stage
        - go get -v -d -t ./...
        - bash testdata/golangci-linter.bash # all, allowed to fail

stages:
  - lint-new
  - lint
  - test

# 'test' stage
script:
  - env
  - bash testdata/travis.bash

env:
  global:
    # GITHUB_TOKEN for automatic releases
    - secure: "at1oJs7ib7glx3W+zk+OkT041LdknVXirIhN403CIihVUrlOhODY7yCTgvF4Rk0jYBJiT35Q2qxpgfWF2qGnsNsQmjG3ydDWQDCepDc/CgXfLyoiSTJK5vTK72dYWTVsBTycXbj1CbSy2X2ah/KWjc4RcgZ67ER7mDpRU5nFeow="
    # Set this to the Go version to use for releases (must appear in version list above).
    - RELEASE_GO_VERSION="1.x"
    # Go versions before go1.13.x will grab master branch unless we use GO111MODULE=on
    # (go1.10.x still needs the workaround in testdata/travis.bash)
    - GO111MODULE="on"
